version: 2
jobs:
  python3.5:
    docker:
      - image: python:3.5
    working_directory: ~/werobot
    steps:
      - checkout
      - run: cat requirements.txt dev-requirements.txt tox-requirements.txt > dependency.txt
      - restore_cache:
          key: v1-python3.5-{{ checksum "dependency.txt" }}
      - run:
          command: |
            cat dev-requirements.txt | grep tox== | xargs pip install codecov
            tox -l | grep py35 | tr '\n' ',' | xargs tox -e && codecov
      - save_cache:
          key: v1-python3.5-{{ checksum "dependency.txt" }}
          paths:
            - .tox
  python3.6:
    docker:
      - image: python:3.6
    working_directory: ~/werobot
    steps:
      - checkout
      - run: cat requirements.txt dev-requirements.txt tox-requirements.txt > dependency.txt
      - restore_cache:
          key: v1-python3.6-{{ checksum "dependency.txt" }}
      - run:
          command: |
            cat dev-requirements.txt | grep tox== | xargs pip install codecov
            tox -l | grep py36 | tr '\n' ',' | xargs tox -e && codecov
      - save_cache:
          key: v1-python3.6-{{ checksum "dependency.txt" }}
          paths:
            - .tox
  python3.7:
    docker:
      - image: python:3.7
    working_directory: ~/werobot
    steps:
      - checkout
      - run: cat requirements.txt dev-requirements.txt tox-requirements.txt > dependency.txt
      - restore_cache:
          key: v1-python3.7-{{ checksum "dependency.txt" }}
      - run:
          command: |
            cat dev-requirements.txt | grep tox== | xargs pip install codecov
            tox -l | grep py37 | tr '\n' ',' | xargs tox -e && codecov
      - save_cache:
          key: v1-python3.7-{{ checksum "dependency.txt" }}
          paths:
            - .tox
  python3.8:
    docker:
      - image: python:3.8
    working_directory: ~/werobot
    steps:
      - checkout
      - run: cat requirements.txt dev-requirements.txt tox-requirements.txt > dependency.txt
      - restore_cache:
          key: v1-python3.8-{{ checksum "dependency.txt" }}
      - run:
          command: |
            cat dev-requirements.txt | grep tox== | xargs pip install codecov
            tox -l | grep py38 | tr '\n' ',' | xargs tox -e && codecov
      - save_cache:
          key: v1-python3.8-{{ checksum "dependency.txt" }}
          paths:
            - .tox
  docs:
    docker:
      - image: python:3.7
    working_directory: ~/werobot
    steps:
      - checkout
      - run: cat requirements.txt dev-requirements.txt tox-requirements.txt > dependency.txt
      - restore_cache:
          key: v1-docs-{{ checksum "dependency.txt" }}
      - run:
          command: |
            cat dev-requirements.txt | grep tox== | xargs pip install
            tox -e docs
      - save_cache:
          key: v1-docs-{{ checksum "dependency.txt" }}
          paths:
            - .tox
  lint:
    docker:
      - image: python:latest
    working_directory: ~/werobot
    steps:
      - checkout
      - run:
          command: |
            cat dev-requirements.txt | grep yapf== | xargs pip install
            yapf -p -r -d docs/ werobot/ tests/ *.py
workflows:
  version: 2
  test:
    jobs:
      - python3.5
      - python3.6
      - python3.7
      - python3.8
      - docs
      - lint
